"""empty message

Revision ID: v2.0.0.a
Revises: v1.3.0.a
Create Date: 2020-06-23 17:32:57.341978

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "v2.0.0.a"
down_revision = "v1.3.0.a"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "trials",
        sa.Column(
            "datetime_last_update",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("trials", "datetime_last_update")
    # ### end Alembic commands ###
