"""empty message

Revision ID: v0.16.0.a
Revises: v0.9.0.a
Create Date: 2019-09-14 15:45:41.458947

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'v0.16.0.a'
down_revision = 'v0.9.0.a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("trials") as batch_op:
        batch_op.alter_column('state',
                              type_=sa.Enum('RUNNING', 'COMPLETE', 'PRUNED',
                                            'FAIL', 'WAITING', name='trialstate'),
                              existing_type=sa.Enum('RUNNING', 'COMPLETE', 'PRUNED',
                                                    'FAIL', name='trialstate'))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("trials") as batch_op:
        batch_op.alter_column('state',
                              type_=sa.Enum('RUNNING', 'COMPLETE', 'PRUNED',
                                            'FAIL', name='trialstate'),
                              existing_type=sa.Enum('RUNNING', 'COMPLETE', 'PRUNED',
                                                    'FAIL', 'WAITING', name='trialstate'))
    # ### end Alembic commands ###
