name: "\U00002753Questions"
description: Please let us know if you have any questions.
labels: ["question"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for your questions!

        If you are more comfortable with [Stack Overflow](https://stackoverflow.com/questions/tagged/optuna), you may consider posting your question with the "optuna" tag there instead.
        Alternatively, for issues that would benefit from more of an interactive session with the developers, you may refer to the [optuna/optuna chat](https://gitter.im/optuna/optuna) on Gitter.
  - type: textarea
    id: environment
    attributes:
      label: Environment
      description: |
        Please give us your environment information. You can get this information by typing the following.
        ```
        python -c 'import optuna; print(optuna.__version__)'
        python -c 'import platform; print(platform.python_version())'
        python -c 'import platform; print(platform.platform())'
        ```
      value: |
        - Optuna version:
        - Python version:
        - OS:
        - (Optional) Other libraries and their versions:
    validations:
      required: true
  - type: textarea
    id: description
    attributes:
      label: Description
      description: |
        Please describe your question.
    validations:
      required: true
  - type: textarea
    id: logs
    attributes:
      label: Error messages, stack traces, or logs
      description: Please copy and paste any relevant error messages, stack traces, or log output. 
      render: shell
    validations:
       required: true
  - type: textarea
    id: steps-to-reproduce
    attributes:
      label: Steps to reproduce
      description: Please provide how we reproduce your reported bugs. If possible, it is highly recommended to provide the reproducible example codes.
      value: |
        1.
        2.
        3.
        ```python
        # python code
        ```
    validations:
      required: true
