# Run tests on Mac, which are triggered by each master push.
# Currently, Python3.12 is only used as an environment.
# This is mainly for the sake of speed.
name: Mac tests

on:
  push:
    branches:
      - master
  pull_request: {}
  schedule:
    - cron: '0 23 * * SUN-THU'
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref == 'refs/heads/master' && github.run_number || github.ref }}
  cancel-in-progress: true

jobs:
  tests-mac:
    runs-on: macos-latest

    # Scheduled Tests are disabled for forks.
    if: (github.event_name == 'schedule' && github.repository == 'optuna/optuna') || (github.event_name != 'schedule')
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Install the latest version of uv
      uses: astral-sh/setup-uv@08807647e7069bb48b6ef5acd8ec9567f424441b # v8.1.0
      with:
        python-version: 3.12
        enable-cache: true

    - name: Install
      run: |
        # Install minimal dependencies and confirm that `import optuna` is successful.
        uv sync --python 3.12
        uv run python -c 'import optuna'
        uv run optuna --version
        uv sync --python 3.12 --group test --extra optional

    - name: Output installed packages
      run: |
        uv pip freeze
    - name: Output dependency tree
      run: |
        uv tree --group test --extra optional


    - name: Scheduled tests
      if:  ${{ github.event_name == 'schedule' || github.event_name == 'workflow_dispatch' }}
      run: |
        uv run pytest tests -n 8
    - name: Tests
      if:  ${{ github.event_name != 'schedule' && github.event_name != 'workflow_dispatch' }}
      run: |
        uv run pytest tests -m "not slow" -n 8
