name: matplotlib-tests

on:
  pull_request:
    paths:
      - .github/workflows/matplotlib-tests.yml
      - optuna/visualization/**.py
      - tests/visualization_tests/**
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref == 'refs/heads/master' && github.run_number || github.ref }}
  cancel-in-progress: true

jobs:
  matplotlib-tests:
    runs-on: ubuntu-latest

    # Scheduled Tests are disabled for forks.
    if: (github.event_name == 'schedule' && github.repository == 'optuna/optuna') || (github.event_name != 'schedule')
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Install the latest version of uv
      uses: astral-sh/setup-uv@08807647e7069bb48b6ef5acd8ec9567f424441b # v8.1.0
      with:
        python-version: 3.12
        enable-cache: true

    - name: Install
      run: |
        # Install minimal dependencies and confirm that `import optuna` is successful.
        uv sync
        uv run python -c 'import optuna'
        uv run optuna --version
        uv sync --group test --extra optional

    - name: Output installed packages
      run: |
        uv pip freeze
    - name: Output dependency tree
      run: |
        uv tree --group test
    - name: Tests without Plotly
      if:  ${{ github.event_name != 'schedule' && github.event_name != 'workflow_dispatch' }}
      run: |
        uv pip uninstall plotly
        uv run pytest tests/visualization_tests/matplotlib_tests -n 8
