name: Reviewdog

on:
  pull_request:
    types: [opened, review_requested]

permissions:
  contents: read
  pull-requests: write

jobs:
  reviewdog:
    runs-on: ubuntu-latest

    if: github.event.action == 'opened' || github.event.requested_team.name == 'reviewdog'

    steps:

    - name: Checkout
      uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

    - name: Install the latest version of uv
      uses: astral-sh/setup-uv@bec219d24cd3e171d82865faccec33120bb574f4 # v10.1.0
      with:
        python-version: 3.12
        enable-cache: true

    - name: Install
      run: |
        uv sync --group checking

    - name: Output installed packages
      run: |
        uv pip freeze
    - name: Output dependency tree
      run: |
        uv tree --group checking

    - name: Apply formatters
      run: |
        uv run ruff check . --fix
        uv run ruff format .

    - name: Reviewdog
      uses: reviewdog/action-suggester@2558ba17e65a9039e73764a73009fc05fef28a46 # v1.24.3
      with:
        tool_name: formatters
