name: Reviewdog

on:
  pull_request:
    types: [opened, review_requested]

permissions:
  contents: read
  pull-requests: write

jobs:
  reviewdog:
    runs-on: ubuntu-latest

    if: github.event.action == 'opened' || github.event.requested_team.name == 'reviewdog'

    steps:

    - name: Checkout
      uses: actions/checkout@v4

    - name: Install the latest version of uv
      uses: astral-sh/setup-uv@08807647e7069bb48b6ef5acd8ec9567f424441b # v8.1.0
      with:
        python-version: 3.12
        enable-cache: true

    - name: Install
      run: |
        uv sync --group checking

    - name: Output installed packages
      run: |
        uv pip freeze
    - name: Output dependency tree
      run: |
        uv tree --group checking

    - name: Apply formatters
      run: |
        uv run ruff check . --fix
        uv run ruff format .

    - name: Reviewdog
      uses: reviewdog/action-suggester@v1
      with:
        tool_name: formatters
