name: z_mxnet

on:
  schedule:
    - cron: '0 15 * * *'
  pull_request:
    paths:
      - 'exampels/mxnet/**'
      - '.github/workflows/z_mxnet.yml'

jobs:
  examples:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.6, 3.7, 3.8, 3.9]

    if: github.repository == 'optuna/optuna'
    steps:
    - uses: actions/checkout@v2
    - name: setup-python${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install (apt)
      run: |
        sudo apt-get update
        sudo apt-get -y install libopenblas-dev
    - name: Install (Python)
      run: |
        python -m pip install --upgrade pip
        pip install --progress-bar off -U setuptools
        python setup.py sdist

        # Install minimal dependencies and confirm that `import optuna` is successful.
        pip install --progress-bar off $(ls dist/*.tar.gz)
        python -c 'import optuna'

        pip install -r examples/mxnet/requirements.txt
    - name: Run examples
      run: |
        python examples/mxnet/gluon_simple.py
        python examples/mxnet/mxnet_simple.py
        python examples/mxnet/mxnet_integration.py
      env:
        OMP_NUM_THREADS: 1
